version: "3.9"

services:
  blog-frontend:
    build:
      context: ./services/blog-frontend
      dockerfile: Dockerfile
    image: blog-frontend:latest
    container_name: blog_frontend
    volumes:
      - ./services/blog-frontend:/usr/src/app
    ports:
      - 3000:3000
  blog-api:
    build:
      context: ./services/blog-api
      dockerfile: Dockerfile
    image: blog-api:latest
    container_name: blog_api
    volumes:
      - ./services/blog-api:/usr/src/app
    ports:
      - 4000:4000
    env_file:
      - ./services/blog-api/.env
    environment:
      - DEV_DB_HOST=db
  db:
    image: mysql
    container_name: db
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: blog

  adminer:
    image: adminer
    container_name: db_manager
    restart: always
    ports:
      - 3310:8080
